stages:
  

  fetch:
    cmd: |
      python pipeline.py fetch
    deps:
      - pipeline.py
      - fetchdata.py
    outs:
      - ${data_dir}/raw/
    

  predict:
    cmd: |
      python pipeline.py predict
    deps:
      - pipeline.py
      - predict.py
      - dataeng.py
      - model.py
      - ${data_dir}/raw/
    outs:
      - ${data_dir}/processed/


vars:
  - data_dir: "data"
  - reports_dir: "reports"
